### ISSUE TITLE
Pokémon Blue randomizer stuck in pre-title loop, even after hard resets; controller not working after closing and reopening ROM

### ISSUE THREAD

**Issue by jangler** [Dabomstew/gambatte-speedrun#16]
After soft resetting during a Pokémon Blue randomizer, I got stuck in a loop in the pre-title screen segments and was unable to get back into the game proper, even after hard resetting (Ctrl+R) multiple times. Closing the ROM and re-opening it via the File menu fixed that problem, but then my controller wasn't recognized at all (not detected in Settings->Input). Things were fine after closing gambatte and opening a new instance.

Recording: https://www.twitch.tv/videos/374931855

Using r649 PSR on Linux. Let me know if there's any more information I should provide.

**Comment by Dabomstew** [comment]
It seems like the emulator stopped detecting your controller and the soft reset inputs were stuck on (requiring a reset of the emulator to make the controller be detected again is fairly normal behavior). Not sure that I can really diagnose this very well past that. Thanks for the report in any case.

**Comment by jangler** [comment]
OK, that's a way more coherent explanation, wow. Without knowing how/why the controller stopped being detected there's not much point in having this issue open then,
