### ISSUE TITLE
Question: Possible to disable on-screen status messages?

### ISSUE THREAD

**Issue by unrealcroissant** [Dabomstew/gambatte-speedrun#5]
I've looked through the settings and didn't find anything, but I figured I'd ask in case I missed something. For clarity, I'm referring to the messages in the lower left of the screen that display when performing a reset/creating or loading a save state.

**Comment by Dabomstew** [comment]
This isn't possible to do right now. In the case of this specific project, that is going to remain the case as the messages are useful during community verification of emulator speedruns. For base gambatte, they probably just didn't see any need to implement such a feature. If your interest isn't in speedrunning, there are other emulators available with similar features and compatibility that do not feature on-screen messages that you could try using, such as bgb.

**Comment by unrealcroissant** [comment]
That makes a lot of sense. I'm still very new to speedrunning and the value of these messages for verification never even occurred to me. I feel a bit silly now for even asking about it. Thanks for explaining it to me! I really appreciate it.
