### ISSUE TITLE
Cannot build on Mac

### ISSUE THREAD

**Issue by nm111** [Dabomstew/gambatte-speedrun#6]
I am trying to build this on MacOS Sierra 10.12.3, but I am getting getting the following error after running `./build_qt.sh`:
`./gambattesource.h:42:27: error: use of undeclared identifier 'GAMBATTE_QT_VERSION_STR'
        void reset() { gb_.reset(GAMBATTE_QT_VERSION_STR); }`.

**Comment by Dabomstew** [comment]
Right now to report the version number on reset the emulator needs to be built out of the cloned git repository, not just a copy of the files. That's all I can imagine is happening here given the specific error.

**Comment by nm111** [comment]
OK thanks, I just realised this on my own though...
