### ISSUE TITLE
make the fadeout upon hard reset optional

### ISSUE THREAD

**Issue by BambooShadow** [Dabomstew/gambatte-speedrun#9]
something that's bugging me since r614:
- I'm still using r604 because the fadeout upon hard reset can't be turned on/off
- I know the pokemon guys like the fadeout (for whatever reason...) but many other speedrun-communities don't need it

Thanks for a great emu nevertheless!

**Comment by Dabomstew** [comment]
This was indirectly addressed by #10 (adds a platform menu) so when another official release comes out other communities can just have runners use GBA as their platform selection (or indeed anything but GBP)

**Comment by Dabomstew** [comment]
The version without fade is (finally) officially available in https://github.com/Dabomstew/gambatte-speedrun/releases/tag/r649 , so this seems resolved.
